# Formative Assignment (amended)

**Deadline: Please see Canvas**

There are 5 exercises in these assignment. Each completed exercise is awarded 7 points for a total of 35 points. In order to pass the final assigment you will need to reach at least 40 points out of 100.

Please send your solutions to the Weekly Classes Office (weeklyclasses@conted.ox.ac.uk) with a signed DoA (Declaration of Authorship) form. Please send the notebook with your name appended to the file name.

In [1]:
## Let's import the libraries we are going to use later on
import numpy as np
import pandas as pd

# Let's set the precision for NumPy and Pandas
np.set_printoptions(precision=3)
pd.options.display.float_format = '{:,.2f}'.format

## Exercises on Data Structures

### 1. Compute statistics on a Python list [7 points]
Given the following list
```
l = [12, 45, 12, 999, 10, 8, 76, 20, 10, 10, 7, 70, 17]
```
Compute the mean, the median and the standard deviation of the values in the list, using only built-in functionalities of python (no imported libraries, no NumPy or Pandas)

In [3]:
l = [12, 45, 12, 999, 10, 8, 76, 20, 10, 10, 7, 70, 17]

# Write your solution here
mean = sum(l) / len(l)

mean


99.6923076923077

### 2A. Create a dictionary from a list of tuples (records) [3 points]

Given the following list of tuples, each one holding a record
```
records = [
    ('author', 'title', 'publication_year', 'page_count'), 
    ('J. R. R. Tolkien', 'The Fellowship of the Ring', 1954, 398),
    ('J. K. Rowling', 'Harry Potter and the Philosopher\'s stone', 1996, 223),
    ('Evelyn Waugh', 'Brideshead Revisited', 1945, 402),
    ('Philip K. Dick', 'Ubik', 1969, 202),
    ('Thomas Pynchon', "Gravity's Rainbow", 1973, 760),
    ('Stephen King', 'The Stand', 1978, 829)
]
```
Convert them into a list of dictionaries, using the first tuple as keys for all the dictionaries and all the other tuples as values, one per dictionary. 
Expected result:

```
books = [{'author': 'J. R. R. Tolkien',
  'title': 'The Fellowship of the Ring',
  'publication_year': 1954,
  'page_count': 398},
 {'author': 'J. K. Rowling',
  'title': "Harry Potter and the Philosopher's stone",
  'publication_year': 1996,
  'page_count': 223},
 {'author': 'Evelyn Waugh',
  'title': 'Brideshead Revisited',
  'publication_year': 1945,
  'page_count': 402},
 {'author': 'Philip K. Dick',
  'title': 'Ubik',
  'publication_year': 1969,
  'page_count': 202},
 {'author': 'Thomas Pynchon',
  'title': "Gravity's Rainbow",
  'publication_year': 1973,
  'page_count': 760},
 {'author': 'Stephen King',
  'title': 'The Stand',
  'publication_year': 1978,
  'page_count': 829}]
```

In [22]:
records = [
    ('author', 'title', 'publication_year', 'page_count'), 
    ('J. R. R. Tolkien', 'The Fellowship of the Ring', 1954, 398),
    ('J. K. Rowling', 'Harry Potter and the Philosopher\'s stone', 1996, 223),
    ('Evelyn Waugh', 'Brideshead Revisited', 1945, 402),
    ('Philip K. Dick', 'Ubik', 1969, 202),
    ('Thomas Pynchon', "Gravity's Rainbow", 1973, 760),
    ('Stephen King', 'The Stand', 1978, 829)
]

## Write your solution here
books = [dict(zip(records[0], x)) for x in records[1:]]

books

[{'author': 'J. R. R. Tolkien',
  'title': 'The Fellowship of the Ring',
  'publication_year': 1954,
  'page_count': 398},
 {'author': 'J. K. Rowling',
  'title': "Harry Potter and the Philosopher's stone",
  'publication_year': 1996,
  'page_count': 223},
 {'author': 'Evelyn Waugh',
  'title': 'Brideshead Revisited',
  'publication_year': 1945,
  'page_count': 402},
 {'author': 'Philip K. Dick',
  'title': 'Ubik',
  'publication_year': 1969,
  'page_count': 202},
 {'author': 'Thomas Pynchon',
  'title': "Gravity's Rainbow",
  'publication_year': 1973,
  'page_count': 760},
 {'author': 'Stephen King',
  'title': 'The Stand',
  'publication_year': 1978,
  'page_count': 829}]

### 2B. Dictionary manipulation [4 points]
Write a function that takes the dictionary like `books` and return the author whose book has the highest page count. 

Apply the function to `books` to verify that it works correctly

In [30]:
## Write your solution here

#TODO improve?

def max_page_count(booklist) :
    max_page = 0
    max_title = ""
    for book in booklist :
        if book["page_count"] > max_page :
            max_page = book["page_count"]
            max_title = book["title"]
    return max_title

max_page_count(books)

'The Stand'

## Exercises on Numpy

For these exercises we will work on the IRIS dataset, a very popular multivariate dataset for data anaylisis, first introduced by Ronald Fisher in 1936.

See more about the IRIS dataset heare: https://archive.ics.uci.edu/ml/datasets/Iris

The data source is the file `iris.data` retrieved from the Web. It contains the data for this example in comma separated values (CSV) format. The number of columns is 5 and the number of rows is 150. The data set is composed of 50 samples from each of three species of Iris Flower: Iris Setosa, Iris Virginica and Iris Versicolor. Four features were measured from each sample: the length and the width of the sepals and petals, in centimetres. Based on the combination of these four features, Fisher developed a linear discriminant model to distinguish the species one from each other.

The variables are:

    sepal_length: Sepal length, in centimeters.
    sepal_width: Sepal width, in centimeters.
    petal_length: Petal length, in centimeters.
    petal_width: Petal width, in centimeters.

The three categories of Irises are: 'Iris Setosa', 'Iris Versicolor', and 'Iris Virginica'. 

Let's first import the `iris` dataset as a 1-dimensional array of tuples.

In [2]:
# Input:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(
    url, delimiter=',', 
    names=['sepal length', 'sepal width', 'petal length', 'petal width', 'species'],
    dtype=[np.float64, np.float64, np.float64, np.float64, 'U15']
)
iris

array([(5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, 'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, 'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, 'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, 'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, 'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, 'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, 'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, 'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, 'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, 'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, 'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, 'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, 'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, 'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, 'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, 'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, 'Iris-setosa'),
       (4.6, 3.6, 1. , 0.2, 'Iri

### 3A. How to convert a 1d array of tuples to a 2d numpy array [4 points]

Exercise: convert the `iris` 1D array to a numeric-only 2D array `iris_data` by omitting the species text field. Create a `iris_label` 1D array containing only the species text field. Keep the same indexing/order as in the original array.

In [3]:
## Write your solution here
iris_labels = [iri[4] for iri in iris]

iris_data = np.array([[iri[0], iri[1], iri[2], iri[3]] for iri in iris])

iris_data


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

### 3B. Split the IRIS dataset by Label [3 points]


Split the dataset in `iris_data` according to the labels `iris_labels`. 

In [4]:
# Write your solution here

#TODO improve?


iris_data_split = dict()

for a in set(iris_labels) :
    iris_data_split[a] = []

for i in range(len(iris_labels)) :
    iris_data_split[iris_labels[i]].append(iris_data[i])

iris_data_split

{'Iris-virginica': [array([6.3, 3.3, 6. , 2.5]),
  array([5.8, 2.7, 5.1, 1.9]),
  array([7.1, 3. , 5.9, 2.1]),
  array([6.3, 2.9, 5.6, 1.8]),
  array([6.5, 3. , 5.8, 2.2]),
  array([7.6, 3. , 6.6, 2.1]),
  array([4.9, 2.5, 4.5, 1.7]),
  array([7.3, 2.9, 6.3, 1.8]),
  array([6.7, 2.5, 5.8, 1.8]),
  array([7.2, 3.6, 6.1, 2.5]),
  array([6.5, 3.2, 5.1, 2. ]),
  array([6.4, 2.7, 5.3, 1.9]),
  array([6.8, 3. , 5.5, 2.1]),
  array([5.7, 2.5, 5. , 2. ]),
  array([5.8, 2.8, 5.1, 2.4]),
  array([6.4, 3.2, 5.3, 2.3]),
  array([6.5, 3. , 5.5, 1.8]),
  array([7.7, 3.8, 6.7, 2.2]),
  array([7.7, 2.6, 6.9, 2.3]),
  array([6. , 2.2, 5. , 1.5]),
  array([6.9, 3.2, 5.7, 2.3]),
  array([5.6, 2.8, 4.9, 2. ]),
  array([7.7, 2.8, 6.7, 2. ]),
  array([6.3, 2.7, 4.9, 1.8]),
  array([6.7, 3.3, 5.7, 2.1]),
  array([7.2, 3.2, 6. , 1.8]),
  array([6.2, 2.8, 4.8, 1.8]),
  array([6.1, 3. , 4.9, 1.8]),
  array([6.4, 2.8, 5.6, 2.1]),
  array([7.2, 3. , 5.8, 1.6]),
  array([7.4, 2.8, 6.1, 1.9]),
  array([7.9, 3.8, 6.

### 4. Compute statistics with Numpy [7 points]

1) For each flower species compute the key statistics for `sepal width`:
- mean
- median
- standard deviation

Answer the following questions:

    a) Which is the flower type with the largest mean value for `sepal_width`?
    b) Which is the flower type with the smallest median value for `sepal_width`?
    
2) Compute the correlation matrix between `sepal_width` and `petal_length` for the three scpecies. Which is the species that shows the highest correlation among the two parameters?

In [55]:
### Compute mean, median, and standard deviation for `sepal width` here:
sepal_width_stats = {}

### names=['sepal length', 'sepal width', 'petal length', 'petal width', 'species']

for iris, data in iris_data_split.items() :
    sepal_width_stats[iris] = {
        'mean': np.mean(data, axis=0)[1],
        'median': np.median(data, axis=0)[1],
        'std': np.std(data, axis=0)[1]
    }

print(sepal_width_stats)


## TODO : clean up

## a
max_sepal_width_mean = sepal_width_stats[next(iter(sepal_width_stats))]['mean']
max_sepal_width_mean_iris = next(iter(sepal_width_stats))


for iris in sepal_width_stats :
    if sepal_width_stats[iris]['mean'] > max_sepal_width_mean :
        max_sepal_width_mean = sepal_width_stats[iris]['mean']
        max_sepal_width_mean_iris = iris

## b
min_sepal_width_median = sepal_width_stats[next(iter(sepal_width_stats))]['median']
min_sepal_width_median_iris = next(iter(sepal_width_stats))

for iris in sepal_width_stats :
    if sepal_width_stats[iris]['median'] < min_sepal_width_median :
        min_sepal_width_median = sepal_width_stats[iris]['median']
        min_sepal_width_median_iris = iris


print(min_sepal_width_median_iris)


{'Iris-virginica': {'mean': 2.9739999999999998, 'median': 3.0, 'std': 0.319255383666431}, 'Iris-setosa': {'mean': 3.4180000000000006, 'median': 3.4, 'std': 0.37719490982779713}, 'Iris-versicolor': {'mean': 2.7700000000000005, 'median': 2.8, 'std': 0.31064449134018135}}
Iris-versicolor


In [8]:
### Compute the correlation coefficients here



### 5. How to create a new column from existing columns of a numpy array [7 points]

Create a new column for the flower volume V in `iris`, where volume is computing according to this formula (the assumption here is that the shape of the iris flower is approximately conical):

$$ Volume = \frac{\pi \times Sepal Length^2 \times Petal Length}{3}$$

In [50]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Write your solution here


### names=['sepal length', 'sepal width', 'petal length', 'petal width', 'species']

volume = (np.pi * (iris_2d[:, 0].astype(float) ** 2) * iris_2d[:, 2].astype(float)) / 3

volume = volume[:, np.newaxis]

iris_2d_with_volume = np.hstack((iris_2d, volume))

iris_2d_with_volume

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa',
        36.65191429188092],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa',
        51.911677007917746],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa',
        31.022180256648003],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa',
        39.269908169872416],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa',
        28.383242427632585],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa',
        37.714819806345474],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa',
        45.80442088933919],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa',
        38.60389052731